// react/src/components/nameList.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Button, Input, List, Modal, Space } from 'antd';
import { ExclamationCircleOutlined, PlusOutlined } from '@ant-design/icons';
import { Name } from '../shared/models/nameCollection';
import { RootState } from '../redux/reducers';
import { NameAdd, NameRemove, NameSetFilter } from '../redux/actions/nameAction';
import { NameDetails } from './nameDetails';
import { NamingRule } from '../shared/models/namingRuleCollection';

interface Props {
  names: Name[];
  namingRules: NamingRule[];
  add: any;
  remove: any;
  setFilter: any;
}

class NamesComponentPure extends React.Component<Props> {
  state = {
    showDetails: false
  };
  remove = (item: Name) => {
    Modal.confirm({
      title: 'Are you sure you want to delete it?',
      icon: <ExclamationCircleOutlined/>,
      content: 'This deletion is un-withdrawable.',
      okText: 'Yes',
      okType: 'danger',
      cancelText: 'No',
      onOk: () => {
        this.props.remove(NameRemove(item));
      }
    });
  };

  add = (item: Name) => {
    this.props.add(NameAdd(item));
    this.setState({showDetails: false});
  };

  filterChanged = (e: any) => {
    const name = e.target.value;
    this.props.setFilter(NameSetFilter({name}));
  };

  render() {
    return (<div>
      <Space>
        <label>Filter by Name:</label>
        <Input onChange={this.filterChanged}/>
      </Space>
      <List dataSource={this.props.names} renderItem={(item) => {
        return (
          <List.Item key={item.id} actions={
            [<Button key={'button' + item.id} type='link' danger={true} onClick={() => this.remove(item)}>Delete</Button>]}>
            {item.name}
          </List.Item>
        );
      }}/>
      <Button type='dashed' block={true} icon={<PlusOutlined/>} onClick={() => this.setState({showDetails: true})}>
        Add a new Name
      </Button>
      {this.state.showDetails ?
        <NameDetails rules={this.props.namingRules} title='Add a Name'
                     onSubmit={this.add} onCancel={() => this.setState({showDetails: false})}/> : null}
    </div>);
  }
}

const mapStore = (state: RootState) => {
  const keyword = state.nameState.nameFilter.name;
  const names = !!keyword ?
    state.nameState.names.items.filter(x => x.name.toLowerCase().startsWith(keyword.toLowerCase())) :
    state.nameState.names.items;
  const namingRules = state.nameState.namingRules.items.filter(x => !x.disabled);
  return {names, namingRules};
};

const mapDispatch = (dispatch: any) => {
  const dispatchAction = (action: any) => dispatch(action);
  return {
    add: dispatchAction,
    remove: dispatchAction,
    setFilter: dispatchAction
  };
};

export const NamesComponent = connect(mapStore, mapDispatch)(NamesComponentPure);

// vue/src/views/names/NameList.vue
<template>
  <a-space>
    <label>Filter by Name:</label>
    <a-input @change="search($event.target.value)"></a-input>
  </a-space>
  <a-list :data-source="names">
    <template #renderItem="{item}">
      <a-list-item :key="item.id">
        <template v-slot:actions>
          <a-button :key="'button' + item.id" type='link' @click="removeItem(item)">Delete</a-button>
        </template>
        {{item.name}}
      </a-list-item>
    </template>

  </a-list>
  <a-button type='dashed' block icon="" @click="showDetails = true">
    Add a new Name
  </a-button>
  <name-details :title="'Add a new Name'" v-if="showDetails" @cancel="showDetails = false" @save="addItem($event)"></name-details>
</template>

<script lang="ts">
import { Options, Vue } from 'vue-class-component'
import NameDetails from '@/views/names/NameDetails.vue'
import { Name } from '@/shared/models/nameCollection'
import { Getter, Action } from 'vuex-class'
import { NameAdd, NameRemove } from '@/shared/constants'
import { Modal } from 'ant-design-vue'
import { ExclamationCircleOutlined } from '@ant-design/icons-vue/lib'
import { createVNode } from 'vue'

@Options({
  components: { NameDetails }
})
export default class NameList extends Vue {
  names: Name[] = [];
  showDetails = false;

  @Getter('getNames') getNames!:(keyword?: string) => Name[]

  @Action(NameRemove) remove!:(payload: Name) => void

  @Action(NameAdd) add!:(payload: Name) => void

  addItem (item: Name): void {
    this.add(item)
    this.showDetails = false
  }

  removeItem (item: Name): void {
    Modal.confirm({
      title: 'Are you sure you want to delete it?',
      icon: createVNode(ExclamationCircleOutlined),
      content: 'This deletion is un-withdrawable.',
      okText: 'Yes',
      okType: 'danger',
      cancelText: 'No',
      onOk: () => {
        this.remove(item)
      }
    })
  }

  search (keyword: string):void {
    this.names = this.getNames(keyword)
  }

  created (): void {
    this.names = this.getNames()
  }
}
</script>
