// react/src/components/namingRuleList.tsx
import React from 'react';
import { connect } from 'react-redux';
import { NamingRule } from '../shared/models/namingRuleCollection';
import {
  NamingRuleAdd,
  NamingRuleDisable,
  NamingRuleEnable,
  NamingRuleRemove,
  NamingRuleSetFilter
} from '../redux/actions/namingRuleAction';
import { Button, List, Modal, Radio, Space, Switch } from 'antd';
import { ExclamationCircleOutlined, PlusOutlined } from '@ant-design/icons';
import { NamingRuleDetails } from './namingRuleDetails';
import { RootState } from '../redux/reducers';

interface Props {
  rules: NamingRule[];
  addRule: any;
  removeRule: any;
  disableRule: any;
  enableRule: any;
  setFilter: any;
}

class NamingRulesComponentPure extends React.Component<Props> {
  state = {
    showDetails: false,
    filter: 'all'
  };

  addNamingRule = (item: NamingRule) => {
    this.props.addRule(NamingRuleAdd(item));
    this.setState({showDetails: false});
  };

  setNamingRuleStatus = (item: NamingRule, enabled: boolean) => {
    if (enabled) {
      this.props.disableRule(NamingRuleEnable(item));
    } else {
      this.props.disableRule(NamingRuleDisable(item));
    }
  };

  delNamingRule = (item: NamingRule) => {
    Modal.confirm({
      title: 'Are you sure you want to delete it?',
      icon: <ExclamationCircleOutlined/>,
      content: 'This deletion is un-withdrawable.',
      okText: 'Yes',
      okType: 'danger',
      cancelText: 'No',
      onOk: () => {
        this.props.removeRule(NamingRuleRemove(item));
      }
    });
  };

  filterChanged = (e: any) => {
    const filterValue = e.target.value;
    const filter = {all: true, disabled: false};
    if (filterValue !== 'all') {
      filter.all = false;
      filter.disabled = filterValue === 'disabled';
    }
    this.props.setFilter(NamingRuleSetFilter(filter));
    this.setState({filter: e.target.value});
  };

  render() {
    return (<div>
      <Space>
        <label>Display:</label>
        <Radio.Group onChange={this.filterChanged} value={this.state.filter}>
          <Radio value='all'>All</Radio>
          <Radio value='disabled'>Disabled</Radio>
          <Radio value='enabled'>Enabled</Radio>
        </Radio.Group>
      </Space>
      <List dataSource={this.props.rules} renderItem={item => (
        <List.Item key={item.id} actions={item.isBuildIn ?
          [<Switch key={'switch' + item.id} checkedChildren='已启用' checked={true} size='small' disabled={true}/>,
            <div key={'div' + item.id} style={{width: 56}}>Build-in</div>] :
          [<Switch key={'switch' + item.id} checkedChildren='已启用' unCheckedChildren='已禁用' checked={!item.disabled}
                   onChange={(v) => this.setNamingRuleStatus(item, v)} size='small'/>,
            <Button key={'button' + item.id} type='link' size='small' danger={true}
                    onClick={() => this.delNamingRule(item)}>Delete</Button>]}>
          <List.Item.Meta title={item.name}
                          description={item.value.map(x => x.type + ': ' + (x.value || 'null')).join(', ')}/>
        </List.Item>
      )}
      />
      <Button type='dashed' block={true} icon={<PlusOutlined/>} onClick={() => this.setState({showDetails: true})}>
        Add a new Naming Rule
      </Button>
      {this.state.showDetails ?
        <NamingRuleDetails title={'Add a Naming Rule'}
                           onSubmit={this.addNamingRule}
                           onCancel={() => this.setState({showDetails: false})}/> : null}
    </div>);
  }
}

const getVisibleRules = (state: RootState): NamingRule[] => {
  if (!state.namingRuleState.namingRuleFilter.all) {
    const disabled = state.namingRuleState.namingRuleFilter.disabled;
    return state.namingRuleState.namingRules.items.filter((x: NamingRule) => x.disabled === disabled);
  }
  return state.namingRuleState.namingRules.items;
};
const mapStoreToProps = (state: RootState) => {
  return {
    rules: getVisibleRules(state)
  };
};

const mapDispatchToProps = (dispatch: any) => {
  const dispatchActon = (action: any) => dispatch(action);
  return {
    addRule: dispatchActon,
    removeRule: dispatchActon,
    disableRule: dispatchActon,
    enableRule: dispatchActon,
    setFilter: dispatchActon
  };
};

export const NamingRulesComponent = connect(mapStoreToProps, mapDispatchToProps)(NamingRulesComponentPure);

// vue/src/views/naming-rules/NamingRuleList.vue
<template>
  <div>
    <a-space>
      <label>Display:</label>
      <a-radio-group @change="filterChanged()" v-model:value="filter">
        <a-radio value='all'>All</a-radio>
        <a-radio value='disabled'>Disabled</a-radio>
        <a-radio value='enabled'>Enabled</a-radio>
      </a-radio-group>
    </a-space>
    <a-list :data-source="rules" >
      <template #renderItem="{item}">
        <a-list-item :key="item.id">
          <template v-slot:actions>
            <a-switch size="small" checked-children="已启用" un-checked-children="已禁用" :checked="!item.disabled"
                      :disabled="item.isBuildIn" @change="setNamingRuleStatus(item, $event)"></a-switch>
            <a-button size="small" v-if="!item.isBuildIn" type='link' @click="removeItem(item)">Delete</a-button>
            <div v-else style="width: 56px">Build-in</div>
          </template>
          <a-list-item-meta :title="item.name" :description="item.value.map(x => x.type + ': ' + (x.value || 'null')).join(', ')"></a-list-item-meta>
        </a-list-item>
      </template>

    </a-list>
    <naming-rule-details v-if="showDetails" title="Add a new Naming Rule" @cancel="showDetails=false" @save="addItem($event)"></naming-rule-details>
    <a-button type='dashed' :block="true" @click="showDetails = true" >
      <template #icon><PlusOutlined /></template>
      Add a new Naming Rule
    </a-button>

  </div>
</template>
<script lang="ts">
import { Options, Vue } from 'vue-class-component'
import { Getter, Action } from 'vuex-class'
import {
  NamingRuleAdd,
  NamingRuleDisable,
  NamingRuleEnable,
  NamingRuleRemove
} from '@/shared/constants'
import { Modal } from 'ant-design-vue'
import { ExclamationCircleOutlined, PlusOutlined } from '@ant-design/icons-vue/lib'
import { createVNode } from 'vue'
import { NamingRule } from '@/shared/models/namingRuleCollection'
import NamingRuleDetails from '@/views/naming-rules/NamingRuleDetails.vue'

@Options({
  components: { NamingRuleDetails, PlusOutlined }
})
export default class NamingRuleList extends Vue {
  rules: NamingRule[] = []
  filter = 'all'
  showDetails = false

  @Getter('getNamingRules') getItems!:(status?: boolean) => NamingRule[]

  @Action(NamingRuleRemove) remove!:(payload: NamingRule) => void

  @Action(NamingRuleAdd) add!:(payload: NamingRule) => void
  @Action(NamingRuleEnable) enable!:(payload: NamingRule) => void
  @Action(NamingRuleDisable) disable!:(payload: NamingRule) => void

  addItem (item: NamingRule): void {
    this.add(item)
    this.showDetails = false
  }

  removeItem (item: NamingRule): void {
    Modal.confirm({
      title: 'Are you sure you want to delete it?',
      icon: createVNode(ExclamationCircleOutlined),
      content: 'This deletion is un-withdrawable.',
      okText: 'Yes',
      okType: 'danger',
      cancelText: 'No',
      onOk: () => {
        this.remove(item)
      }
    })
  }

  setNamingRuleStatus (item: NamingRule, enabled: boolean): void {
    if (enabled) {
      this.enable(item)
    } else {
      this.disable(item)
    }
  }

  filterChanged (): void {
    if (this.filter === 'all') {
      this.rules = this.getItems()
    } else {
      const disabled = this.filter === 'disabled'
      this.rules = this.getItems(disabled)
    }
  }

  created (): void {
    this.rules = this.getItems()
  }
}
</script>
