// vue/src/views/About.vue
<template>
  <p>The Naming Rule Management is a project for learning react and Vue.</p>
  <p>It has two versions, the react version is built by react-scripts with react 17.x, react-router-dom 5.x, react-redux
    7.x, TypeScript.</p>
  <p>The Vue version is built by vue/cli with Vue 3.x, Vuex 4.x, Vue router 4.x, TypeScript.</p>
  <p>
    It has two repositories, the GitHub one is at
    <a href='https://github.com/ckvip/naming-rule'
       target='github'> https://github.com/ckvip/naming-rule</a>, and it has a
    <a href='https://ckvip.github.io/naming-rule' target='demo'> react live demo</a>.
  </p>
  <p>
    The other one is on Gitee.com in China at
    <a href='https://gitee.com/yoso2020/naming-rule'
       target='gitee'> https://gitee.com/yoso2020/naming-rule</a>, it has a
    <a href='https://yoso2020.gitee.io/naming-rule' target='demo'>react live demo</a> too.
  </p>
</template>

// react/src/components/about.tsx
import React from 'react';

export class AboutComponent extends React.Component {
    render() {
        return (
            <div>
                <p>The Naming Rule Management is a project for learning react and Vue.</p>
                <p>It has two versions, the react version is built by react-scripts with react 17.x, react-router-dom
                    5.x, react-redux 7.x, TypeScript.</p>
                <p>The Vue version is built by vue/cli with Vue 3.x, Vuex 4.x, Vue router 4.x, TypeScript.</p>
                <p>
                    It has two repositories, the GitHub one is at
                    <a href='https://github.com/ckvip/naming-rule'
                       target='github'> https://github.com/ckvip/naming-rule</a>, and it has a
                    <a href='https://ckvip.github.io/naming-rule' target='demo'> react live demo</a>.
                </p>
                <p>
                    The other one is on Gitee.com in China at
                    <a href='https://gitee.com/yoso2020/naming-rule'
                       target='gitee'> https://gitee.com/yoso2020/naming-rule</a>, it has a
                    <a href='https://yoso2020.gitee.io/naming-rule' target='demo'>react live demo</a> too.
                </p>
            </div>
        );
    }
}
